"""empty message

Revision ID: fdac7dd6997f
Revises: d6ab39700f4f
Create Date: 2022-11-24 12:47:13.585032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdac7dd6997f'
down_revision = 'd6ab39700f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('species'),
    sa.UniqueConstraint('species'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('type')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('dimension', sa.String(length=120), nullable=False),
    sa.Column('residents', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension'),
    sa.UniqueConstraint('dimension'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('residents'),
    sa.UniqueConstraint('residents'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('vehicles')
    op.add_column('favorites', sa.Column('character_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.alter_column('favorites', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'favorites', 'planet', ['planet_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'character', ['character_id'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.alter_column('favorites', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('favorites', 'planet_id')
    op.drop_column('favorites', 'character_id')
    op.create_table('vehicles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_vehicle', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='vehicles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('people',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_people', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='people_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('planets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_planet', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='planets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
